name: "PanelSense"
version: "0.0.3"
slug: panel_sense
description: >-
  "Add-on helps to manage PanelSense Android app, that can be used to work with Home Assistant."
arch:
  - amd64
url: "https://github.com/dawidpodolak/PanelSense-Ha-addon"
ports:
  123/tcp: 123
  8652/tcp: 8652
map:
  - config:rw
  - ssl
