name: "PanelSense"
version: "1.0.0"
slug: panel_sense
description: "Add-on helps to manage PanelSense Android app, that can be used to work with Home Assistant."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/dawidpodolak/PanelSense-Ha-addon"
ports:
  80/tcp: null
  123/tcp: 123
  8652/tcp: 8652
ports_description:
  80/tcp: Web interface (Not required for Ingress)
map:
  - config:rw
  - ssl
init: false
hassio_api: true
homeassistant_api: true
hassio_role: default
options:
  server_user: "admin"
  server_password: "admin"
  ssl: false
schema:
  server_user: str
  server_password: str
  ssl: bool

ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:home-circle-outline